const DATA={...window.WHB_CORE,recipes:(window.WHB_RECIPE_CHUNKS||[]).flat()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const baseOwned=new Set(DATA.owned.map(norm));
const pantry=new Set((DATA.inventory['Assumed Staples']||[]).map(norm));
const requiredWines=['Prosecco','Sparkling Wine','Dry Red Wine','Dry White Wine','Dry Rosé','Fino Sherry','Amontillado Sherry','Ruby Port','White Port','Madeira'];
const state={favorites:new Set(JSON.parse(localStorage.getItem('whb_favorites')||'[]')),ratings:JSON.parse(localStorage.getItem('whb_ratings')||'{}'),notes:JSON.parse(localStorage.getItem('whb_notes')||'{}'),inventory:JSON.parse(localStorage.getItem('whb_inventory_v2')||'{}'),favOnly:false,current:null};
const equivalents={'jameson':['jameson irish whiskey'],'irish whiskey':['jameson irish whiskey'],'long road cherry':['long road cherry liqueur'],'cherry liqueur':['long road cherry liqueur'],'fabrizia pistachio':['fabrizia pistachio liqueur'],'pistachio liqueur':['fabrizia pistachio liqueur'],'egg':['eggs'],'egg white':['eggs'],'cream':['heavy cream','cream or half and half'],'coffee liqueur':['kahlua'],'rosemary':['fresh rosemary'],'basil':['fresh basil'],'spiced rum':['captain morgan spiced rum'],'triple sec cointreau':['triple sec'],'orange curacao':['triple sec'],'sparkling wine':['prosecco'],'aged rum':['plantation original dark rum'],'white rum':['bacardi white rum'],'dark rum':['plantation original dark rum'],'brandy':['apple brandy'],'rye':['sazerac rye'],'bourbon':['1792 bourbon','willett small batch bourbon','woodinville bourbon'],'vodka':['tito s vodka','wheatley vodka','soft parade vodka'],'gin':['new amsterdam stratosphere gin','sovereign gin','grey whale gin','long road michigin gin'],'rum':['bacardi white rum','plantation original dark rum','plantation pineapple rum'],'tequila':['jose cuervo tequila','casino azul tequila'],'mezcal':['monte alban mezcal'],'aquavit':['long road aquavit','barrel aged aquavit'],'absinthe':['long road absinthe']};
const composites={'rosemary syrup':['fresh rosemary','simple syrup'],'honey syrup':['honey','water'],'honey ginger syrup':['honey','ginger beer'],'lemon soda':['lemon juice','soda water','simple syrup']};
function override(n){return Object.prototype.hasOwnProperty.call(state.inventory,n)?state.inventory[n]:null}
function presentName(n){let o=override(n);return o===null?baseOwned.has(n):o}
function matchIngredient(name){let n=norm(name);if(presentName(n))return{status:pantry.has(n)?'pantry':'exact',via:name};let eq=equivalents[n]||[];let hit=eq.find(presentName);if(hit)return{status:'substitute',via:hit};let parts=composites[n];if(parts&&parts.every(presentName))return{status:'substitute',via:parts.join(' + ')};let partial=[...baseOwned].find(o=>o.startsWith(n+' ')||n.startsWith(o+' '));if(partial&&n.length>5&&presentName(partial))return{status:'substitute',via:partial};return{status:'missing',via:null}}
function missing(r){return[...new Set(r.ingredients.filter(x=>matchIngredient(x[0]).status==='missing').map(x=>x[0]))]}
function scaleAmount(s,m){return String(s).replace(/(\d+\s+\d+\/\d+|\d+\/\d+|\d+(?:\.\d+)?)/g,v=>{let n;if(v.includes(' ')){let[a,b]=v.split(' '),[c,d]=b.split('/');n=+a+(+c/+d)}else if(v.includes('/')){let[a,b]=v.split('/');n=+a/+b}else n=+v;let z=n*m;return Number.isInteger(z)?String(z):String(Math.round(z*100)/100)})}
function provenance(r){if(r.source)return r.source;if(r.tags.includes('IBA Classic'))return'Verified classic';if(r.tags.includes('Modern Classic'))return'Established modern recipe';if(r.tags.includes('Craft'))return'Wright Home Bar craft recipe';return'Catalog recipe'}
function fillFilters(){[...new Set(DATA.recipes.map(r=>r.base))].sort().forEach(v=>$('#base').insertAdjacentHTML('beforeend',`<option>${v}</option>`));[...new Set(DATA.recipes.flatMap(r=>r.tags))].sort().forEach(v=>$('#tag').insertAdjacentHTML('beforeend',`<option>${v}</option>`))}
function card(r){let miss=missing(r),rt=state.ratings[r.id]||0;return`<article class="card ${miss.length?'card-missing':''}" onclick="openRecipe(${r.id})"><div class="cardtop"><h3>${r.name}</h3><span class="status ${miss.length?'miss':''}">${miss.length?`Missing ${miss.length}`:'Make now'}</span></div><div class="tags">${r.tags.slice(0,4).map(t=>`<span class="tag">${t}</span>`).join('')}</div><p class="tasting">${r.tasting}</p>${miss.length?`<div class="missing-list"><b>Missing:</b> ${miss.map(x=>`<span>${x}</span>`).join('')}</div>`:''}<div class="cardfooter"><span>${'★'.repeat(rt)}${'☆'.repeat(5-rt)}</span><button onclick="event.stopPropagation();toggleFav(${r.id})">${state.favorites.has(r.id)?'♥':'♡'}</button></div></article>`}
function filtered(){let q=norm($('#search').value),base=$('#base').value,tag=$('#tag').value,av=$('#availability').value,rf=$('#ratingFilter').value;let rows=DATA.recipes.filter(r=>{let blob=norm([r.name,r.base,r.style,r.tasting,provenance(r),...r.tags,...r.ingredients.flat()].join(' ')),mc=missing(r).length,rt=state.ratings[r.id]||0;return(!q||blob.includes(q))&&(!base||r.base===base)&&(!tag||r.tags.includes(tag))&&(!av||(av==='make'?mc===0:av==='one'?mc===1:mc>0))&&(!rf||rt>=+rf)&&(!state.favOnly||state.favorites.has(r.id))});let s=$('#sort').value;if(s==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));if(s==='rating')rows.sort((a,b)=>(state.ratings[b.id]||0)-(state.ratings[a.id]||0)||a.name.localeCompare(b.name));if(s==='missing')rows.sort((a,b)=>missing(a).length-missing(b).length||a.name.localeCompare(b.name));if(s==='random')rows.sort(()=>Math.random()-.5);return rows}
function renderRecipes(){let rows=filtered();$('#recipeGrid').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No cocktails match those filters.</div>';$('#count').textContent=`${rows.length} shown`;stats()}
function allInventoryItems(){let recipeItems=DATA.recipes.flatMap(r=>r.ingredients.map(x=>x[0]));return[...new Set([...DATA.owned,...requiredWines,...recipeItems])].sort()}
function categoryOf(x){let n=norm(x);if(/wine|prosecco|sherry|port|madeira|vermouth|rosé/.test(n))return'Wine & Fortified';if(/juice|syrup|cream|soda|tonic|cola|beer|coffee|egg|mint|basil|rosemary|sugar|salt|water|purée/.test(n))return'Mixers & Pantry';if(/liqueur|aperol|campari|fernet|midori|kahlua|chartreuse|cassis|limoncello|st germain|amaro|falernum|orgeat/.test(n))return'Liqueurs & Modifiers';return'Spirits'}
function renderInventory(){let q=norm($('#inventorySearch').value),groups={};allInventoryItems().filter(x=>!q||norm(x).includes(q)).forEach(x=>(groups[categoryOf(x)]??=[]).push(x));$('#inventoryGroups').innerHTML=Object.entries(groups).map(([g,items])=>`<div class="inventory-group"><h3>${g}</h3>${items.map(x=>{let n=norm(x),checked=presentName(n),uses=DATA.recipes.filter(r=>r.ingredients.some(i=>norm(i[0])===n)).length;return`<label class="inventory-item"><input type="checkbox" ${checked?'checked':''} onchange="setInventory('${encodeURIComponent(n)}',this.checked)"><span><b>${x}</b><small>${uses} direct recipe uses${pantry.has(n)?' · pantry assumption':''}</small></span></label>`}).join('')}</div>`).join('')}
function setInventory(k,v){state.inventory[decodeURIComponent(k)]=v;localStorage.setItem('whb_inventory_v2',JSON.stringify(state.inventory));renderInventory();renderRecipes();renderBottles();optimizer();buildMenu()}window.setInventory=setInventory;
function renderBottles(){let bottles=DATA.inventory['Base Spirits'].concat(DATA.inventory['Liqueurs & Aperitifs'],DATA.inventory['Fortified Wine'],requiredWines);$('#bottleGrid').innerHTML=bottles.map(b=>{let exact=DATA.recipes.filter(r=>r.ingredients.some(x=>norm(x[0])===norm(b)||matchIngredient(x[0]).via===norm(b))).length,favs=DATA.recipes.filter(r=>state.favorites.has(r.id)&&r.ingredients.some(x=>norm(x[0])===norm(b))).length,untried=DATA.recipes.filter(r=>!state.ratings[r.id]&&r.ingredients.some(x=>norm(x[0])===norm(b))).length;return`<div class="bottle" onclick="useBottle('${b.replace(/'/g,"&#39;")}')"><strong>${b}</strong><div class="metrics">${presentName(norm(b))?'In your bar':'Not in inventory'}<br>${exact} recipes · ${favs} favorites · ${untried} untried</div></div>`}).join('')}
function useBottle(b){switchView('recipes');$('#search').value=b;renderRecipes()}window.useBottle=useBottle;
function optimizer(){let map={};DATA.recipes.forEach(r=>{let m=missing(r);if(m.length===1)map[m[0]]=(map[m[0]]||0)+1});let rows=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,30);$('#optimizer').innerHTML=rows.map(([x,n],i)=>`<div class="buycard" onclick="showUnlocks('${encodeURIComponent(x)}')"><small>#${i+1} next purchase</small><b>${x}</b><span class="unlock">+${n}</span><span>recipes unlocked · click to view</span></div>`).join('');$('#sUnlock').textContent=rows[0]?.[1]||0}
function showUnlocks(k){let x=decodeURIComponent(k);switchView('recipes');$('#search').value='';$('#availability').value='';let rows=DATA.recipes.filter(r=>{let m=missing(r);return m.length===1&&m[0]===x});$('#recipeGrid').innerHTML=rows.map(card).join('');$('#count').textContent=`${rows.length} unlocked by ${x}`}window.showUnlocks=showUnlocks;
function pick(pool,used){let options=pool.filter(r=>!used.has(r.id));if(!options.length)options=pool;if(!options.length)return DATA.recipes.find(r=>missing(r).length===0);let r=options[Math.floor(Math.random()*options.length)];used.add(r.id);return r}
function buildMenu(){let make=DATA.recipes.filter(r=>missing(r).length===0),u=new Set(),slots=[['Aperitif',pick(make.filter(r=>r.tags.includes('Low ABV')||r.style==='Aperitivo'),u)],['Main Cocktail',pick(make.filter(r=>['Sour','Spirit-forward','Tiki','Wine'].includes(r.style)),u)],['Dessert Cocktail',pick(make.filter(r=>r.tags.includes('Dessert')||r.style==='Dessert'),u)],['Nightcap',pick(make.filter(r=>r.style==='Spirit-forward'||r.style==='Hot'),u)]];$('#menuGrid').innerHTML=slots.map(([l,r])=>`<div class="menuslot"><h3>${l}</h3><strong>${r.name}</strong><p>${r.tasting}</p><button class="btn alt" onclick="openRecipe(${r.id})">Open recipe</button></div>`).join('')}
function openRecipe(id){let r=DATA.recipes.find(x=>x.id===id);state.current=r;$('#mName').textContent=r.name;$('#mTags').innerHTML=r.tags.map(t=>`<span class="tag">${t}</span>`).join('');$('#mTaste').textContent=r.tasting;$('#mProvenance').textContent=provenance(r);let mult=+$('#batch').value;$('#mIngredients').innerHTML=r.ingredients.map(([a,b])=>{let m=matchIngredient(a),cls=m.status==='missing'?'ingredient-missing':m.status==='substitute'?'ingredient-substitute':m.status==='pantry'?'ingredient-pantry':'';let note=m.status==='missing'?'Missing from your bar':m.status==='substitute'?`Available via ${m.via}`:m.status==='pantry'?'Pantry assumption':'Exact inventory match';return`<li class="${cls}"><span>${a}<em>${note}</em></span><b>${scaleAmount(b,mult)}</b></li>`}).join('');$('#mInstructions').textContent=r.instructions;$('#mGlass').textContent=r.glass;$('#mGarnish').textContent=r.garnish;$('#mNotes').value=state.notes[id]||'';renderRating();$('#toggleFavModal').textContent=state.favorites.has(id)?'Remove favorite':'Add favorite';$('#modal').classList.add('open')}window.openRecipe=openRecipe;
function renderRating(){let v=state.ratings[state.current.id]||0;$('#mRating').innerHTML='<b>Your rating:</b> '+[1,2,3,4,5].map(n=>`<button onclick="rate(${n})">${n<=v?'★':'☆'}</button>`).join('')}function rate(n){state.ratings[state.current.id]=n;localStorage.setItem('whb_ratings',JSON.stringify(state.ratings));renderRating();renderRecipes()}window.rate=rate;
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('whb_favorites',JSON.stringify([...state.favorites]));renderRecipes();renderBottles()}window.toggleFav=toggleFav;
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='inventory')renderInventory();if(id==='backup')renderBackup()}window.switchView=switchView;
function randomFrom(p){if(p.length)openRecipe(p[Math.floor(Math.random()*p.length)].id)}
function backupData(){return{version:2,exported:new Date().toISOString(),favorites:[...state.favorites],ratings:state.ratings,notes:state.notes,inventory:state.inventory}}
function renderBackup(){$('#backupText').value=JSON.stringify(backupData(),null,2)}
function exportBackup(){let blob=new Blob([JSON.stringify(backupData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wright-home-bar-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importBackup(){try{let d=JSON.parse($('#backupText').value);state.favorites=new Set(d.favorites||[]);state.ratings=d.ratings||{};state.notes=d.notes||{};state.inventory=d.inventory||{};localStorage.setItem('whb_favorites',JSON.stringify([...state.favorites]));localStorage.setItem('whb_ratings',JSON.stringify(state.ratings));localStorage.setItem('whb_notes',JSON.stringify(state.notes));localStorage.setItem('whb_inventory_v2',JSON.stringify(state.inventory));alert('Backup imported.');renderRecipes();renderInventory();renderBottles();optimizer()}catch(e){alert('That backup could not be read.')}}
function resetInventory(){if(confirm('Reset inventory changes to the original catalog defaults?')){state.inventory={};localStorage.removeItem('whb_inventory_v2');renderInventory();renderRecipes();optimizer()}}
function stats(){$('#sRecipes').textContent=DATA.recipes.length;$('#sMake').textContent=DATA.recipes.filter(r=>missing(r).length===0).length;$('#sBottles').textContent=allInventoryItems().filter(x=>presentName(norm(x))).length;$('#sRated').textContent=Object.keys(state.ratings).length;$('#sFav').textContent=state.favorites.size}
['search','base','tag','availability','ratingFilter','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderRecipes));$('#inventorySearch').addEventListener('input',renderInventory);$('#favoritesOnly').onclick=()=>{state.favOnly=!state.favOnly;renderRecipes()};$('#clearFilters').onclick=()=>{['search','base','tag','availability','ratingFilter'].forEach(id=>$('#'+id).value='');state.favOnly=false;renderRecipes()};$('#randomAny').onclick=()=>randomFrom(DATA.recipes);$('#randomMake').onclick=()=>randomFrom(DATA.recipes.filter(r=>missing(r).length===0));$('#randomWild').onclick=()=>randomFrom(DATA.recipes.filter(r=>r.tags.includes('Craft')||r.tags.includes('Tiki')||r.tags.includes('Wine Cocktail')));$('#buildMenu').onclick=buildMenu;$$('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#batch').onchange=()=>{if(state.current)openRecipe(state.current.id)};$('#saveNotes').onclick=()=>{if(state.current){state.notes[state.current.id]=$('#mNotes').value;localStorage.setItem('whb_notes',JSON.stringify(state.notes))}};$('#toggleFavModal').onclick=()=>{if(state.current)toggleFav(state.current.id)};$('#exportBackup').onclick=exportBackup;$('#importBackup').onclick=importBackup;$('#resetInventory').onclick=resetInventory;
fillFilters();renderRecipes();renderBottles();renderInventory();optimizer();buildMenu();renderBackup();stats();