const DATA={...window.WHB_CORE,recipes:(window.WHB_RECIPE_CHUNKS||[]).flat()};

const state={favorites:new Set(JSON.parse(localStorage.getItem('whb_favorites')||'[]')),ratings:JSON.parse(localStorage.getItem('whb_ratings')||'{}'),notes:JSON.parse(localStorage.getItem('whb_notes')||'{}'),favOnly:false,current:null};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),ownedNames=DATA.owned.map(norm),ownedSet=new Set(ownedNames);
const genericNames=new Set(['gin','vodka','rum','white rum','dark rum','aged rum','bourbon','rye','whiskey','irish whiskey','tequila','mezcal','aquavit','absinthe','brandy','cream','coffee','egg','egg white','lime','lemon','orange','mint','basil','rosemary']);
const equivalentNames={'jameson':['jameson irish whiskey'],'irish whiskey':['jameson irish whiskey'],'long road cherry':['long road cherry liqueur'],'cherry liqueur':['long road cherry liqueur'],'fabrizia pistachio':['fabrizia pistachio liqueur'],'pistachio liqueur':['fabrizia pistachio liqueur'],'egg':['eggs'],'egg white':['eggs'],'cream':['heavy cream','cream or half and half'],'coffee liqueur':['kahlua'],'rosemary':['fresh rosemary'],'basil':['fresh basil'],'spiced rum':['captain morgan spiced rum']};
const compositeIngredients={'rosemary syrup':['fresh rosemary','simple syrup']};
function singular(n){if(n.endsWith('ies'))return n.slice(0,-3)+'y';if(n.endsWith('s')&&!n.endsWith('ss'))return n.slice(0,-1);return n}
function matchesOwnedName(n){if(ownedSet.has(n))return true;let sn=singular(n);if(ownedNames.some(o=>singular(o)===sn))return true;if(!genericNames.has(n)&&n.length>=6&&ownedNames.some(o=>o.startsWith(n+' ')||n.startsWith(o+' ')))return true;return false}
function isOwned(i){let n=norm(i);if(matchesOwnedName(n))return true;let direct=DATA.aliases[i]||[];if(direct.some(x=>matchesOwnedName(norm(x))))return true;let equivalents=equivalentNames[n]||[];if(equivalents.some(matchesOwnedName))return true;let parts=compositeIngredients[n];if(parts&&parts.every(matchesOwnedName))return true;return false}function missing(r){return [...new Set(r.ingredients.map(x=>x[0]).filter(x=>!isOwned(x)))]}function scaleAmount(s,m){return s.replace(/(\d+\s+\d+\/\d+|\d+\/\d+|\d+(?:\.\d+)?)/g,v=>{let n;if(v.includes(' ')){let[a,b]=v.split(' '),[c,d]=b.split('/');n=+a+(+c/+d)}else if(v.includes('/')){let[a,b]=v.split('/');n=+a/+b}else n=+v;let z=n*m;return Number.isInteger(z)?String(z):String(Math.round(z*100)/100)})}
function fillFilters(){[...new Set(DATA.recipes.map(r=>r.base))].sort().forEach(v=>$('#base').insertAdjacentHTML('beforeend',`<option>${v}</option>`));[...new Set(DATA.recipes.flatMap(r=>r.tags))].sort().forEach(v=>$('#tag').insertAdjacentHTML('beforeend',`<option>${v}</option>`))}
function card(r){let miss=missing(r),mc=miss.length,rt=state.ratings[r.id]||0,missingLine=mc?`<div class="missing-list"><b>Missing:</b> ${miss.map(x=>`<span>${x}</span>`).join('')}</div>`:'';return `<article class="card ${mc?'card-missing':''}" onclick="openRecipe(${r.id})"><div class="cardtop"><h3>${r.name}</h3><span class="status ${mc?'miss':''}">${mc?`Missing ${mc}`:'Make now'}</span></div><div class="tags">${r.tags.slice(0,4).map(t=>`<span class="tag">${t}</span>`).join('')}</div><p class="tasting">${r.tasting}</p>${missingLine}<div class="cardfooter"><span>${'★'.repeat(rt)}${'☆'.repeat(5-rt)}</span><button onclick="event.stopPropagation();toggleFav(${r.id})">${state.favorites.has(r.id)?'♥':'♡'}</button></div></article>`}
function filtered(){let q=norm($('#search').value),base=$('#base').value,tag=$('#tag').value,av=$('#availability').value,rf=$('#ratingFilter').value;let rows=DATA.recipes.filter(r=>{let blob=norm([r.name,r.base,r.style,r.tasting,...r.tags,...r.ingredients.flat()].join(' ')),mc=missing(r).length,rt=state.ratings[r.id]||0;return(!q||blob.includes(q))&&(!base||r.base===base)&&(!tag||r.tags.includes(tag))&&(!av||(av==='make'?mc===0:mc===1))&&(!rf||rt>=+rf)&&(!state.favOnly||state.favorites.has(r.id))});let s=$('#sort').value;if(s==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));if(s==='rating')rows.sort((a,b)=>(state.ratings[b.id]||0)-(state.ratings[a.id]||0));if(s==='missing')rows.sort((a,b)=>missing(a).length-missing(b).length);if(s==='random')rows.sort(()=>Math.random()-.5);return rows}
function renderRecipes(){let rows=filtered();$('#recipeGrid').innerHTML=rows.map(card).join('');$('#count').textContent=`${rows.length} shown`;stats()}
function bottleSvg(n){let h=[...n].reduce((a,c)=>a+c.charCodeAt(0),0),w=40+h%14;return `<svg viewBox="0 0 90 150"><rect x="38" y="8" width="14" height="28" rx="3" fill="#3d2418"/><path d="M${45-w/2} 36 Q${40-w/2} 45 ${40-w/2} 58 L${40-w/2} 132 Q${40-w/2} 140 ${48-w/2} 140 H${42+w/2} Q${50+w/2} 140 ${50+w/2} 132 L${50+w/2} 58 Q${50+w/2} 45 ${45+w/2} 36Z" fill="#6b4027" stroke="#2b1812" stroke-width="2"/><rect x="${49-w/2}" y="70" width="${w-8}" height="38" fill="#d8c7a8" stroke="#2b1812"/><line x1="${54-w/2}" y1="84" x2="${36+w/2}" y2="84" stroke="#7b2e2b" stroke-width="3"/></svg>`}
function renderBottles(){let b=[...DATA.inventory['Base Spirits'],...DATA.inventory['Liqueurs & Aperitifs'],...DATA.inventory['Fortified Wine']];$('#bottleGrid').innerHTML=b.map(x=>`<div class="bottle" onclick="useBottle('${x.replace(/'/g,"&#39;")}')">${bottleSvg(x)}<strong>${x}</strong><span>Click to filter recipes</span></div>`).join('')}
function useBottle(b){switchView('recipes');$('#search').value=b;renderRecipes()}window.useBottle=useBottle;
function optimizer(){let mp={};DATA.recipes.forEach(r=>{let m=missing(r);if(m.length===1)mp[m[0]]=(mp[m[0]]||0)+1});let rows=Object.entries(mp).sort((a,b)=>b[1]-a[1]).slice(0,24);$('#optimizer').innerHTML=rows.map(([x,n],i)=>`<div class="buycard"><small>#${i+1} next purchase</small><b>${x}</b><span class="unlock">+${n}</span><span>recipes unlocked</span></div>`).join('');$('#sUnlock').textContent=rows[0]?.[1]||0}
function pick(p,u){let a=p.filter(r=>!u.has(r.id));if(!a.length)a=p;let r=a[Math.floor(Math.random()*a.length)];u.add(r.id);return r}
function buildMenu(){let make=DATA.recipes.filter(r=>missing(r).length===0),u=new Set(),slots=[['Aperitif',pick(make.filter(r=>r.tags.includes('Low ABV')||r.style==='Aperitivo'),u)],['Main Cocktail',pick(make.filter(r=>['Sour','Spirit-forward','Tiki'].includes(r.style)),u)],['Dessert Cocktail',pick(make.filter(r=>r.tags.includes('Dessert')||r.style==='Dessert'),u)],['Nightcap',pick(make.filter(r=>r.style==='Spirit-forward'||r.style==='Hot'),u)]];$('#menuGrid').innerHTML=slots.map(([l,r])=>`<div class="menuslot"><h3>${l}</h3><strong>${r.name}</strong><p>${r.tasting}</p><button class="btn alt" onclick="openRecipe(${r.id})">Open recipe</button></div>`).join('')}
function openRecipe(id){let r=DATA.recipes.find(x=>x.id===id);state.current=r;$('#mName').textContent=r.name;$('#mTags').innerHTML=r.tags.map(t=>`<span class="tag">${t}</span>`).join('');$('#mTaste').textContent=r.tasting;let mult=+$('#batch').value,miss=new Set(missing(r));$('#mIngredients').innerHTML=r.ingredients.map(([a,b])=>`<li class="${miss.has(a)?'ingredient-missing':''}"><span>${a}${miss.has(a)?'<em>Missing from your bar</em>':''}</span><b>${scaleAmount(b,mult)}</b></li>`).join('');$('#mInstructions').textContent=r.instructions;$('#mGlass').textContent=r.glass;$('#mGarnish').textContent=r.garnish;$('#mNotes').value=state.notes[id]||'';renderRating();$('#toggleFavModal').textContent=state.favorites.has(id)?'Remove favorite':'Add favorite';$('#modal').classList.add('open')}window.openRecipe=openRecipe;
function renderRating(){let v=state.ratings[state.current.id]||0;$('#mRating').innerHTML='<b>Your rating:</b> '+[1,2,3,4,5].map(n=>`<button onclick="rate(${n})">${n<=v?'★':'☆'}</button>`).join('')}function rate(n){state.ratings[state.current.id]=n;localStorage.setItem('whb_ratings',JSON.stringify(state.ratings));renderRating();renderRecipes()}window.rate=rate;
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('whb_favorites',JSON.stringify([...state.favorites]));renderRecipes()}window.toggleFav=toggleFav;
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}function randomFrom(p){if(p.length)openRecipe(p[Math.floor(Math.random()*p.length)].id)}function stats(){$('#sRecipes').textContent=DATA.recipes.length;$('#sMake').textContent=DATA.recipes.filter(r=>missing(r).length===0).length;$('#sBottles').textContent=DATA.owned.length;$('#sRated').textContent=Object.keys(state.ratings).length;$('#sFav').textContent=state.favorites.size}
['search','base','tag','availability','ratingFilter','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',renderRecipes));$('#favoritesOnly').onclick=()=>{state.favOnly=!state.favOnly;renderRecipes()};$('#clearFilters').onclick=()=>{['search','base','tag','availability','ratingFilter'].forEach(id=>$('#'+id).value='');state.favOnly=false;renderRecipes()};$('#randomAny').onclick=()=>randomFrom(DATA.recipes);$('#randomMake').onclick=()=>randomFrom(DATA.recipes.filter(r=>missing(r).length===0));$('#randomWild').onclick=()=>randomFrom(DATA.recipes.filter(r=>r.tags.includes('Craft')||r.tags.includes('Tiki')));$('#buildMenu').onclick=buildMenu;$$('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#closeModal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#batch').onchange=()=>{if(state.current)openRecipe(state.current.id)};$('#saveNotes').onclick=()=>{if(state.current){state.notes[state.current.id]=$('#mNotes').value;localStorage.setItem('whb_notes',JSON.stringify(state.notes))}};$('#toggleFavModal').onclick=()=>{if(state.current)toggleFav(state.current.id)};
fillFilters();renderRecipes();renderBottles();optimizer();buildMenu();stats();