(()=>{
const recentKey='whb_discovery_recent_v4',prefsKey='whb_discovery_prefs_v4';
const loadLocal=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
let recent=loadLocal(recentKey,[]),prefs=loadLocal(prefsKey,{availability:'make',base:'',mood:'',difficulty:'',history:'untried'});
function savePrefs(){localStorage.setItem(prefsKey,JSON.stringify(prefs))}
function remember(ids){recent=[...ids,...recent.filter(x=>!ids.includes(x))].slice(0,60);localStorage.setItem(recentKey,JSON.stringify(recent))}
function difficulty(r){return r.difficulty||((r.ingredients||[]).length>5?'Intermediate':'Easy')}
function moodMatch(r,m){if(!m)return true;const blob=norm([r.name,r.base,r.style,r.tasting,...(r.tags||[]),...(r.ingredients||[]).flat()].join(' '));const map={refreshing:['refreshing','highball','collins','fizz','spritz','soda','cucumber','mint'],strong:['spirit forward','old fashioned','manhattan','strong','sazerac'],sweet:['dessert','cream','coffee','vanilla','pistachio','chocolate'],bitter:['bitter','campari','aperol','fernet','amaro','cynar'],tropical:['tiki','tropical','pineapple','coconut','passion fruit','guava','mango'],smoky:['mezcal','smoky','smoke'],floral:['floral','elderflower','lavender','rose water','orange flower'],savory:['savory','tomato','celery','cucumber','salt'],weird:['absinthe','fernet','aquavit','chartreuse','matcha','celery','weird','craft']};return(map[m]||[]).some(x=>blob.includes(norm(x)))}
function historyMatch(r,h){const x=hist(r.id);if(!h)return true;if(h==='untried')return x.count===0;if(h==='tried')return x.count>0;if(h==='again')return x.makeAgain;if(h==='stale'){if(!x.lastMade)return true;return(Date.now()-new Date(x.lastMade+'T12:00:00').getTime())/86400000>90}return true}
function availabilityMatch(r,a){const n=missing(r).length;if(a==='make')return n===0;if(a==='one')return n<=1;if(a==='two')return n<=2;return true}
function eligible(){return DATA.recipes.filter(r=>availabilityMatch(r,prefs.availability)&&(!prefs.base||r.base===prefs.base)&&moodMatch(r,prefs.mood)&&(!prefs.difficulty||difficulty(r)===prefs.difficulty)&&historyMatch(r,prefs.history))}
function weightedPick(pool,count){const unseen=pool.filter(r=>!recent.includes(r.id));let source=unseen.length>=count?unseen:pool.filter(r=>recent.indexOf(r.id)>14);if(source.length<count)source=pool;const chosen=[];while(source.length&&chosen.length<count){source.sort((a,b)=>{const ha=hist(a.id),hb=hist(b.id),sa=(ha.count?0:8)+(state.favorites.has(a.id)?3:0)+(ha.makeAgain?2:0)+Math.random()*6,sb=(hb.count?0:8)+(state.favorites.has(b.id)?3:0)+(hb.makeAgain?2:0)+Math.random()*6;return sb-sa});const r=source.shift();chosen.push(r);source=source.filter(x=>x.id!==r.id)}return chosen}
function renderDiscovery(){const pool=eligible(),picks=weightedPick(pool,3);remember(picks.map(x=>x.id));const el=document.getElementById('discoveryResults');if(!el)return;el.innerHTML=picks.length?picks.map(r=>`<div class="tonight-card"><div class="tags">${(r.tags||[]).slice(0,3).map(t=>`<span class="tag">${t}</span>`).join('')}</div><h3>${r.name}</h3><p>${r.tasting||''}</p><p><b>${missing(r).length?`Missing ${missing(r).length}`:'Make now'}</b> · ${difficulty(r)}</p><button class="btn" onclick="openRecipe(${r.id})">Open recipe</button></div>`).join(''):'<div class="empty">No drinks match those discovery filters.</div>';document.getElementById('discoveryCount').textContent=`${pool.length} eligible · ${recent.length} recently suppressed`}
function resetRecent(){recent=[];localStorage.removeItem(recentKey);renderDiscovery()}
function addDiscoveryUI(){const tonight=document.getElementById('tonight');if(!tonight||document.getElementById('discoveryPanel'))return;const panel=document.createElement('div');panel.id='discoveryPanel';panel.className='discovery-panel';panel.innerHTML=`<div class="sectionhead"><h2>Drink Discovery</h2><span id="discoveryCount"></span></div><div class="discovery-filters"><label>Availability<select id="discoverAvailability"><option value="make">Make now</option><option value="one">Missing at most one</option><option value="two">Missing at most two</option><option value="all">Ignore inventory</option></select></label><label>Base<select id="discoverBase"><option value="">Dealer's choice</option></select></label><label>Mood<select id="discoverMood"><option value="">Any mood</option><option value="refreshing">Refreshing</option><option value="strong">Strong</option><option value="sweet">Sweet</option><option value="bitter">Bitter</option><option value="tropical">Tropical</option><option value="smoky">Smoky</option><option value="floral">Floral</option><option value="savory">Savory</option><option value="weird">Unusual</option></select></label><label>Difficulty<select id="discoverDifficulty"><option value="">Any difficulty</option><option value="Easy">Easy</option><option value="Intermediate">Intermediate</option></select></label><label>History<select id="discoverHistory"><option value="">Any history</option><option value="untried">Never made</option><option value="stale">Not made in 90 days</option><option value="tried">Tried</option><option value="again">Make again</option></select></label></div><div class="actions"><button id="discoverButton">Discover three</button><button id="resetDiscovery" class="alt">Reset recent history</button></div><div id="discoveryResults" class="tonight-results"></div>`;tonight.prepend(panel);[...new Set(DATA.recipes.map(r=>r.base))].sort().forEach(v=>document.getElementById('discoverBase').insertAdjacentHTML('beforeend',`<option>${v}</option>`));const ids={discoverAvailability:'availability',discoverBase:'base',discoverMood:'mood',discoverDifficulty:'difficulty',discoverHistory:'history'};Object.entries(ids).forEach(([id,k])=>{const el=document.getElementById(id);el.value=prefs[k]||'';el.onchange=()=>{prefs[k]=el.value;savePrefs()}});document.getElementById('discoverButton').onclick=renderDiscovery;document.getElementById('resetDiscovery').onclick=resetRecent;renderDiscovery();const old=document.getElementById('randomAny');if(old)old.textContent='Discover a drink';if(old)old.onclick=()=>{switchView('tonight');renderDiscovery()};const make=document.getElementById('randomMake');if(make)make.onclick=()=>{prefs.availability='make';prefs.history='untried';savePrefs();switchView('tonight');renderDiscovery()};const wild=document.getElementById('randomWild');if(wild)wild.onclick=()=>{prefs.mood='weird';prefs.availability='make';savePrefs();switchView('tonight');renderDiscovery()}}
window.addEventListener('DOMContentLoaded',addDiscoveryUI);
})();